import { Inter } from "next/font/google";
import "./globals.css";
import {TrackingProvider} from "../context/Tracking";
import { Navbar,Footer } from "@/components/index";

const inter = Inter({ subsets: ["latin"] });

export const metadata = {
  title: "Supply Chain",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={inter.className}>

        <TrackingProvider>
        <Navbar/>
        
        {children}
        <Footer/>
        </TrackingProvider>
        </body>
    </html>
  );
}
